name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:    
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist bdist_wheel
        pip3 install dist/flearn-0.0.1.tar.gz
    - name: Test
      run: |
        cd flearn/test/
        python test_pipline.py
        cd client 
        python test_trainer.py
        python test_DLClient.py
        cd ../server
        python test_communicator.py
        
    # - name: Test Server
    #   run: |
    #     cd ControlledFederatedLearning/test/server
    #     python test_server.py